name: logic_study
description: "Education Courses App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  backdrop: ^0.9.1
  video_player: ^2.8.2
  get: ^4.6.6
  lottie: ^3.0.0
  device_preview: ^1.1.0
  iconsax: ^0.0.8
  kr_builder: ^1.0.5
  kr_button: ^1.0.1
  flutter_svg: ^2.0.9
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  cloud_firestore: ^4.15.3
  firebase_database: ^10.4.0
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  rate_my_app: ^2.0.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  package_info_plus: ^5.0.1
  blur: ^3.1.0
  uuid: ^4.3.3
  recase: ^4.1.0
  kr_pull_down_button: ^1.0.1
  intl: ^0.18.1
  path_provider: ^2.1.2
  datasource:
    path: packages/datasource
  admin:
    path: packages/admin
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  firebase_feature_flag: ^1.0.8
  custom_refresh_indicator: ^3.0.0
  readmore: ^2.2.0
  flutter_sliding_box: ^1.1.5
  pod_player: ^0.2.1
  dio: ^5.4.1
  pay: ^1.1.2
  motion_toast: ^2.8.0
  jaguar_jwt: ^3.0.0
  webviewx_plus: ^0.5.0
  http: ^1.2.0
  open_file: ^3.3.2
  no_screenshot: ^0.0.1+6
  flutter_sticky_header: ^0.6.5
  kr_paginate_firestore: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/images/bg.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/fg.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/svg/
    - assets/

  fonts:    
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn.ttf

