name: admin
description: Dart package which manages save and restore data.
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  datasource:
    path: ../datasource
  get_storage: ^2.1.1
  syncfusion_flutter_datagrid: ^24.2.6
  get: ^4.6.6
  highlight_text: ^1.7.0
  iconsax: ^0.0.8
  kr_pull_down_button: ^1.0.1
  recase: ^4.1.0
  intl: ^0.18.1
  open_file: ^3.3.2
  flutter_spinkit: ^5.2.0
  kr_builder: ^1.0.5
  syncfusion_flutter_datagrid_export: ^24.2.6
  syncfusion_flutter_xlsio: ^24.2.6
  blur: ^3.1.0
  kr_button: ^1.0.1
  url_launcher: ^6.2.4
  kr_extensions: ^1.0.4
  cached_network_image: ^3.3.1
  image_cropper: ^5.0.1
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_advanced_switch: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
